name: tf-init-and-validate
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  init-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Initialize OpenTofu
        run: tofu init
      - name: Validate
        run: tofu validate
      - name: Plan
        env:
          TF_VAR_test_server_ami: ${{ secrets.TF_VAR_test_server_ami }}
          TF_VAR_test_server_availability_zone: ${{ secrets.TF_VAR_test_server_availability_zone }}
          TF_VAR_test_server_instance_type: ${{ secrets.TF_VAR_test_server_instance_type }}
        run: tofu plan -out plan.out 